// pay/src/components/StorageImage.vue
<script setup lang="ts">
import { OG_STORAGE_PREFIX, isOgStorageRef } from "@/scripts/ogStorage";
import OgStorage from "@/scripts/ogStorage";
import { computed, onBeforeUnmount, onMounted, ref, watchEffect } from "vue";

const props = defineProps<{
  alt?: string;
  src?: string;
  rootHash?: string;
  url?: string;
}>();

const resolvedAlt = computed(() => props.alt || "Storage Image");
const resolvedUrl = ref<string | null>(props.url || null);
const loading = ref<boolean>(false);
let objectUrl: string | null = null;

function normalizeOgRef(value: string): string {
  if (isOgStorageRef(value)) return value;
  return `${OG_STORAGE_PREFIX}${value}`;
}

function isDirectUrl(value: string): boolean {
  const v = value.trim();
  return (
    v.startsWith("http://") ||
    v.startsWith("https://") ||
    v.startsWith("blob:") ||
    v.startsWith("data:") ||
    v.startsWith("/")
  );
}

const resolvedRootHash = computed<string | null>(() => {
  const direct =
    typeof props.rootHash === "string" && props.rootHash.trim()
      ? props.rootHash.trim()
      : null;
  if (direct) return direct;

  const src = typeof props.src === "string" ? props.src.trim() : "";
  if (!src) return null;
  if (isDirectUrl(src)) return null;

  return src;
});

function cleanupObjectUrl() {
  if (objectUrl) URL.revokeObjectURL(objectUrl);
  objectUrl = null;
}

async function loadFromStorage(rootHashOrRef: string) {
  loading.value = true;
  try {
    const buffer = await OgStorage.download(normalizeOgRef(rootHashOrRef));
    if (buffer) {
      cleanupObjectUrl();
      objectUrl = URL.createObjectURL(new Blob([buffer]));
      resolvedUrl.value = objectUrl;
    }
  } catch (error) {
    console.error(error);
  } finally {
    loading.value = false;
  }
}

watchEffect(() => {
  if (props.url) {
    resolvedUrl.value = props.url;
    return;
  }

  const src = typeof props.src === "string" ? props.src.trim() : "";
  if (src && isDirectUrl(src)) {
    resolvedUrl.value = src;
  }
});

onMounted(async () => {
  if (resolvedUrl.value) return;
  if (!resolvedRootHash.value) return;
  await loadFromStorage(resolvedRootHash.value);
});

onBeforeUnmount(() => {
  cleanupObjectUrl();
});
</script>

<template>
  <img :src="resolvedUrl || '/images/placeholder.png'" :alt="resolvedAlt" />
</template>

// app/src/components/storage-image.tsx
import * as React from "react";
import Storage from "@/lib/storage";

const PLACEHOLDER_SRC = "/images/placeholder.png";

export type StorageImageProps = {
  alt?: string;
  /** May be a direct URL/path or a 0G root hash string (non-direct). */
  src?: string;
  rootHash?: string;
  url?: string;
} & Omit<React.ImgHTMLAttributes<HTMLImageElement>, "alt" | "src">;

function isDirectUrl(value: string): boolean {
  const v = value.trim();
  return (
    v.startsWith("http://") ||
    v.startsWith("https://") ||
    v.startsWith("blob:") ||
    v.startsWith("data:") ||
    v.startsWith("/")
  );
}

function resolvedRootHashFromProps(
  rootHash: string | undefined,
  src: string | undefined,
): string | null {
  const direct =
    typeof rootHash === "string" && rootHash.trim()
      ? rootHash.trim()
      : null;
  if (direct) return direct;

  const s = typeof src === "string" ? src.trim() : "";
  if (!s) return null;
  if (isDirectUrl(s)) return null;

  return s;
}

export function StorageImage({
  alt = "Storage Image",
  src,
  rootHash,
  url,
  ...imgProps
}: StorageImageProps) {
  const [resolvedUrl, setResolvedUrl] = React.useState<string | null>(
    url?.trim() ?? null,
  );
  /** Blob URLs created from OG downloads (revoked on replace / unmount). */
  const objectUrlRef = React.useRef<string | null>(null);

  const resolvedRootHash = React.useMemo(
    () => resolvedRootHashFromProps(rootHash, src),
    [rootHash, src],
  );

  React.useEffect(() => {
    if (url?.trim()) {
      setResolvedUrl(url.trim());
      return;
    }
    const s = src?.trim() ?? "";
    if (s && isDirectUrl(s)) {
      setResolvedUrl(s);
    }
  }, [url, src]);

  React.useEffect(() => {
    if (url?.trim()) return;

    const s = src?.trim() ?? "";
    if (s && isDirectUrl(s)) return;

    const rh = resolvedRootHash;
    if (!rh) return;

    let cancelled = false;

    (async () => {
      try {
        const buffer = await Storage.download(rh);
        if (cancelled || !buffer) return;

        if (objectUrlRef.current) {
          URL.revokeObjectURL(objectUrlRef.current);
          objectUrlRef.current = null;
        }

        const next = URL.createObjectURL(new Blob([buffer]));
        if (cancelled) {
          URL.revokeObjectURL(next);
          return;
        }

        objectUrlRef.current = next;
        setResolvedUrl(next);
      } catch (error) {
        console.error(error);
      }
    })();

    return () => {
      cancelled = true;
      if (objectUrlRef.current) {
        URL.revokeObjectURL(objectUrlRef.current);
        objectUrlRef.current = null;
      }
    };
  }, [url, src, resolvedRootHash]);

  return (
    <img
      {...imgProps}
      src={resolvedUrl ?? PLACEHOLDER_SRC}
      alt={alt}
    />
  );
}
